suppressMessages(library(data.table))
suppressMessages(library(seqinr))
suppressMessages(library(stringr))
suppressMessages(library(doParallel))
suppressMessages(library(argparse))

# Initialize argument parser
p <- ArgumentParser(description="Calculate methylation levels")
p$add_argument('-n','--cores', type="integer",help='Number of cores')
p$add_argument("-i", "--input", type="character", help="Input directory path", required=TRUE)

args <- p$parse_args(commandArgs(TRUE))
args$cores <- 1
opts <- args

####### bed ######## 
bed_dir <- "/path/to/bed" # bed dir
bedfiles <- list.files(bed_dir, pattern = "^1Mb.bed$") # bed file

# loop
for (a in 1:length(bedfiles)){
  bedfile <- file.path(bed_dir, bedfiles[a])
  ndr.metadata <- fread(bedfile)
  ndr.metadata.gch <- ndr.metadata[,.(V1,V2,V3)] %>% setnames(c("chr","start","end"))
  temp <- unlist(strsplit(bedfiles[a], '[.]'))
  bedname <- basename(bedfile)

  ## input ## 
  io <- list()
  io$indir <- args$input

  ## output ##
  io$outdir <- paste0("/path/to/bed.metlevel/",bedname)
  dir.create(io$outdir)

  files <- list.files(io$indir, pattern = "\\.CG\\.txt\\.gz$") # Per-CpG methylation files generated by Bismark, *CpG_report.txt.gz
  files

  registerDoParallel(cores=args$cores)

# -------------------------
# Main processing loop
# -------------------------
# For each BED annotation file, compute methylation levels
# for all samples in parallel
  invisible(foreach(i=1:length(files)) %dopar% {
    sample=files[i]
    sample <- gsub("\\.CG\\.txt\\.gz$", "", basename(sample))
    anno=ndr.metadata.gch

    dat_sample <- fread(cmd = sprintf("zcat < %s", shQuote(file.path(io$indir, files[i]))), sep="\t", header="auto", verbose=F, showProgress=F)
    dat_sample <- dat_sample[,.(chr=V1,pos=V2,rate=V4/(V4+V5))]  # V4 = methylated reads, V5 = unmethylated reads
    dat_sample <- dat_sample[,c("start","end") := list(pos,pos)][,pos:=NULL] %>% .[,chr:=as.factor(chr)] %>% setkey(chr,start,end)

    fname.out <- sprintf("%s/%s.%s.CG.level.tsv",io$outdir,sample,bedname)

    ## Overlap CpG sites with genomic regions
    setkey(anno,chr,start,end)
    ov <- foverlaps(dat_sample, anno, nomatch=0) %>% .[,"i.end":=NULL] %>% setnames("i.start","pos")
    ov <- ov[,ID:=paste(chr,start,end,sep = "_")]
    out <- ov[,c("sample","anno") := list(sample,bedname)]  %>% .[,.(rate=mean(rate), weight=.N), keyby=.(sample,anno,ID)]
    fwrite(out, fname.out, quote=FALSE, sep="\t", col.names=TRUE, row.names=FALSE)
  
  })

}

print("Processing complete")